from __future__ import annotations

from retrieval.models import (
    Blocker,
    Entity,
    TeamContext,
    WaterlooAffinityEvidence,
)

"""
This mock data was generated by an LLM: I fed the models.py dataclasses into ChatGPT 5 and asking it to generate test data based on a internal tooling problem I encountered during an orbital PR
"""


def get_mock_entities() -> list[Entity]:
    return [
        Entity(
            entity_id="ent-mapbox",
            name="Mapbox",
            entity_type="provider",
            summary="Geospatial mapping platform with APIs for maps, navigation, and telemetry visualization.",
            tags=["geospatial", "mapping", "telemetry", "developer-tools"],
            support_types=["software_credits", "technical_guidance"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-cesium",
            name="Cesium",
            entity_type="provider",
            summary="3D geospatial platform used for digital twins, satellite visualization, and real-time spatial analytics.",
            tags=["geospatial", "mapping", "3d-visualization", "satellite"],
            support_types=["technical_guidance", "integration_support"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-esri",
            name="Esri",
            entity_type="provider",
            summary="GIS tooling and spatial analytics software for mapping, operations, and infrastructure teams.",
            tags=["geospatial", "mapping", "gis", "analytics"],
            support_types=["software_licenses", "training"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-aws",
            name="AWS",
            entity_type="provider",
            summary="Cloud platform offering compute, storage, and grants/credits for startups and student projects.",
            tags=["cloud", "compute", "simulation", "infrastructure"],
            support_types=["cloud_credits", "technical_guidance"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-gcp",
            name="Google Cloud",
            entity_type="provider",
            summary="Cloud services for scalable compute, geospatial analysis, and data processing.",
            tags=["cloud", "compute", "geospatial", "data-platform"],
            support_types=["cloud_credits", "architecture_review"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-waterloo-geo",
            name="Waterloo Geospatial Systems",
            entity_type="company",
            summary="Waterloo-founded startup focused on mapping pipelines for autonomous and aerospace systems.",
            tags=["geospatial", "mapping", "aerospace", "systems-engineering"],
            support_types=["mentorship", "technical_guidance"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="alumni_link",
                    text="Founded by Waterloo Engineering alumni and recruits co-op students.",
                    source_url="https://example.com/waterloo-geospatial",
                )
            ],
        ),
        Entity(
            entity_id="ent-uw-maps-lab",
            name="UW Spatial Intelligence Lab",
            entity_type="lab",
            summary="University lab researching geospatial perception, mapping, and remote sensing.",
            tags=["geospatial", "mapping", "remote-sensing", "research"],
            support_types=["technical_guidance", "research_collaboration"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="official_page",
                    text="Official University of Waterloo research lab.",
                    source_url="https://uwaterloo.ca/",
                )
            ],
        ),
        Entity(
            entity_id="ent-prof-chen",
            name="Professor Chen",
            entity_type="professor",
            summary="Faculty member focused on satellite telemetry, navigation systems, and ground-station software.",
            tags=["satellite", "telemetry", "ground-station", "mapping"],
            support_types=["technical_guidance", "mentorship"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="official_page",
                    text="Current Waterloo professor working on satellite systems.",
                    source_url="https://uwaterloo.ca/",
                )
            ],
        ),
        Entity(
            entity_id="ent-prof-patel",
            name="Professor Patel",
            entity_type="professor",
            summary="Researches embedded systems firmware and low-level hardware reliability.",
            tags=["embedded", "firmware", "hardware", "reliability"],
            support_types=["technical_guidance", "mentorship"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="official_page",
                    text="Current Waterloo ECE faculty member.",
                    source_url="https://uwaterloo.ca/",
                )
            ],
        ),
        Entity(
            entity_id="ent-notion",
            name="Notion",
            entity_type="provider",
            summary="Documentation and knowledge management platform for team onboarding and collaboration.",
            tags=["documentation", "onboarding", "knowledge-base", "productivity"],
            support_types=["software_credits", "training"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-github",
            name="GitHub",
            entity_type="provider",
            summary="Development platform with issue tracking, CI, and project collaboration tooling.",
            tags=["developer-tools", "documentation", "collaboration", "ci-cd"],
            support_types=["software_credits", "technical_guidance"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-altium",
            name="Altium",
            entity_type="provider",
            summary="PCB design software and workflows used for electronics and hardware prototyping.",
            tags=["pcb", "hardware", "electronics", "design-tools"],
            support_types=["software_licenses", "technical_guidance"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-waterloo-rf",
            name="Waterloo RF Labs",
            entity_type="lab",
            summary="Lab specializing in RF communication systems, antennas, and CubeSat communication stacks.",
            tags=["rf", "communication", "cubesat", "antennas"],
            support_types=["technical_guidance", "research_collaboration"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="official_page",
                    text="Official Waterloo RF research lab.",
                    source_url="https://uwaterloo.ca/",
                ),
                WaterlooAffinityEvidence(
                    type="team_sponsor",
                    text="Has advised Waterloo student design teams in prior terms.",
                    source_url="https://example.com/rf-lab-support",
                ),
            ],
        ),
        Entity(
            entity_id="ent-digikey",
            name="DigiKey",
            entity_type="company",
            summary="Electronics distributor with programs for prototyping components and PCB workflows.",
            tags=["pcb", "electronics", "hardware", "supply-chain"],
            support_types=["discounts", "component_support"],
            waterloo_affinity_evidence=[],
        ),
        Entity(
            entity_id="ent-uw-systems",
            name="Waterloo Systems Engineering Group",
            entity_type="company",
            summary="Waterloo alumni-led consultancy offering systems engineering mentorship for student teams.",
            tags=["systems-engineering", "mentorship", "architecture", "aerospace"],
            support_types=["mentorship", "technical_guidance"],
            waterloo_affinity_evidence=[
                WaterlooAffinityEvidence(
                    type="alumni_link",
                    text="Led by Waterloo alumni with previous design-team mentorship.",
                    source_url="https://example.com/uw-systems",
                )
            ],
        ),
    ]


def get_mock_team_context() -> TeamContext:
    return TeamContext(
        team_name="UW Orbital",
        repo="uw-orbital/flight-software",
        active_blockers=[
            Blocker(
                summary="Ground station map view cannot reliably display telemetry position updates.",
                tags=["ground-station", "mapping", "telemetry", "geospatial"],
                severity="high",
            ),
            Blocker(
                summary="Simulation environment is compute-constrained for trajectory testing.",
                tags=["simulation", "cloud", "compute"],
                severity="medium",
            ),
        ],
        subsystems=["ground station", "flight software", "telemetry"],
        inferred_support_needs=["software_credits", "technical_guidance", "cloud_credits"],
        context_summary=(
            "UW Orbital is currently blocked on ground-station mapping and telemetry visualization, "
            "and needs practical support for geospatial tooling plus cloud simulation capacity."
        ),
    )
